---
- block:
  - name: Install Cosmic Desktop Environment
    pacman:
      name:
        - cosmic
        - power-profiles-daemon
      state: present

  - name: Enable and start the service cosmic-greeter
    systemd:
      name: cosmic-greeter
      enabled: true
  become: true